
version: '3.1'


volumes:
  postgresDB:

networks:
  user-service:
    driver: bridge
    

services:
  greet:
    build: .
    container_name: greet3
    env_file: 
      - .env
    restart: always
    networks:
      - user-service
    ports:
      - 8080:8080
  
