
version: '3.7'

networks: 
  default: 
    external: 
      name: user-network

services:
  user:
    image: aws-user-service:latest
    container_name: user
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file: 
      - .env
    # ports:
    #   - 8000:8000
    #   - 9000:9000
  
