version: '3.7'

volumes:
  postgresDB:

networks: 
  default: 
    external: 
      name: user-network

services:
  postgres:
    image: postgres:10.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pgpass'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgresDB
    ports:
      - 5432:5432


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    volumes:
      - postgresDB
    ports:
     - 8081:80
